import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/login');
  await page.getByRole('textbox', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Login' }).fill('justynka');
  await page.getByRole('textbox', { name: 'Hasło' }).click();
  await page.getByRole('textbox', { name: 'Hasło' }).fill('password');
  await page.getByRole('button', { name: 'Zaloguj' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: 'Light' }).click();
  await page.getByRole('button', { name: 'Dark' }).click();
  await page.getByRole('button', { name: 'Add Project' }).click();
  await page.locator('input[name="name"]').click();
  await page.locator('input[name="name"]').click();
  await page.locator('input[name="name"]').fill('proj');
  await page.locator('input[name="name"]').click();
  await page.locator('input[name="name"]').fill('projpr');
  await page.locator('input[name="name"]').click();
  await page.locator('input[name="description"]').click();
  await page.locator('input[name="description"]').fill('dd');
  await page.locator('input[name="name"]').click();
  await page.locator('input[name="name"]').click();
  await page.locator('input[name="description"]').click();
  await page.locator('input[name="description"]').fill('ddffffss');
  await page.getByRole('button', { name: 'Light' }).click();
  await page.getByRole('button', { name: 'Dark' }).click();
  await page.locator('input[name="description"]').click();
  await page.locator('input[name="description"]').fill('ddffffssdddf');
  await page.getByRole('button', { name: 'Add Project' }).click();
  await page.getByRole('button', { name: 'Select' }).nth(2).click();
  await page.getByRole('button', { name: 'Add Story' }).click();
  await page.locator('input[name="title"]').click();
  await page.locator('input[name="title"]').fill('gffff');
  await page.locator('input[name="description"]').click();
  await page.locator('input[name="description"]').fill('ff');
  await page.locator('select[name="priority"]').selectOption('medium');
  await page.getByText('Add Story').click();
  await page.getByRole('button', { name: 'Details' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'Kanban' }).click();
  await page.getByRole('button', { name: 'Add Task' }).click();
  await page.locator('input[type="text"]').click();
  await page.locator('input[type="text"]').fill('gfgg');
  await page.locator('textarea').click();
  await page.getByRole('spinbutton').dblclick();
  await page.locator('form').getByRole('button', { name: 'Add Task' }).click();
  await page.getByTestId('task-todo').click();
  await page.getByRole('combobox').selectOption('2');
  await page.getByRole('button', { name: 'Assign & Start' }).click();
  await page.getByTestId('task-doing').click();
  await page.getByRole('button', { name: 'Mark as Done' }).click();
  await page.getByRole('button', { name: 'Back' }).click();
  await page.getByRole('button', { name: 'Back' }).click();
  await page.getByRole('button', { name: 'Delete' }).nth(2).click();
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: 'Logout' }).click();
  await page.waitForTimeout(1000);
});